//
//  RepositoryTests-RepositoryMocks.generated.swift
//  Repository
//
//  Generated by Mockingbird v0.19.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import Repository
import Combine
import Foundation
import Swift

// No mocks used in 'RepositoryTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
